### ISSUE TITLE
[BUG] Не работает бот

### ISSUE THREAD

**Issue by LeonusDH** [JoCat/manaka-bot#3]
Бот не работает, и я нашёл причину.
У бота нет дельфинов.

**Comment by JoCat** [comment]
У меня всё работает, попробуй выключить и включить.

**Comment by LeonusDH** [comment]
Попробовал. Не может подключиться к серверу PornHub

**Comment by JoCat** [comment]
Ну хз даже, пошевели проводочками, я не знаю...

**Comment by LeonusDH** [comment]
Пошевелил. К серверу подключился, но теперь не ловит сигнал из глубин космоса

**Comment by JoCat** [comment]
Ну тут я уже ничем помочь не могу, увы у меня нет диплома инженера систем космической связи 🤷‍♂️
